### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'xsSimpleType' of undefined

### ISSUE THREAD

**Issue by avmay99** [pocketbitcoin/xsd-tools#3]
I tried to convert gbxml schema under https://github.com/GreenBuildingXML/gbXML_Schemas to typescript but failed with following message:

(node:12488) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'xsSimpleType' of undefined
    at generate (D:\projects\xsdconverter\node_modules\@xsd-tools\typescript\dist\generate.js:29:32)
    at D:\projects\xsdconverter\node_modules\@xsd-tools\typescript\dist\bin\xsd-ts.js:62:52
    at step (D:\projects\xsdconverter\node_modules\@xsd-tools\typescript\dist\bin\xsd-ts.js:34:23)
    at Object.next (D:\projects\xsdconverter\node_modules\@xsd-tools\typescript\dist\bin\xsd-ts.js:15:53)
    at fulfilled (D:\projects\xsdconverter\node_modules\@xsd-tools\typescript\dist\bin\xsd-ts.js:6:58)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:12488) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rudolfbyker** [comment]
Here is a more readable error message:
```
…/node_modules/@xsd-tools/typescript/dist/generate.js:29
    var simpleTypes = xsSchema.xsSimpleType.map(function (s) { return (0, simple_type_1.generateFromSimpleType)(s); });
                               ^

TypeError: Cannot read properties of undefined (reading 'xsSimpleType')
    at generate (…/node_modules/@xsd-tools/typescript/dist/generate.js:29:32)
    at …/node_modules/@xsd-tools/typescript/dist/bin/xsd-ts.js:62:52
    at step (…/node_modules/@xsd-tools/typescript/dist/bin/xsd-ts.js:34:23)
    at Object.next (…/node_modules/@xsd-tools/typescript/dist/bin/xsd-ts.js:15:53)
    at fulfilled (…/node_modules/@xsd-tools/typescript/dist/bin/xsd-ts.js:6:58)

Node.js v24.0.0
```
